version: "3.7"
services: 
    dev:
        image: "node:16.20.2-alpine"
        working_dir: "/srv"
        command: "npm run develop"
        tty: true
        volumes: 
            - "./:/srv/"
        ports: 
            - "8080:8080"
