backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
    - name: "articles"
      label: "Article" 
      folder: "articles"
      create: true 
      slug: "{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Abstract", name: "abstract", widget: "text"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Author", name: "author", widget: "string"}
        - {label: "Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "home"
      label: "Home" 
      folder: "home"
      create: false 
      slug: "{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string"}
        - {label: "HeaderTitle", name: "headerTitle", widget: "string"}
        - {label: "HeaderAbstract", name: "headerAbstract", widget: "text"}
        - {label: "HeaderImage", name: "headerImage", widget: "image"}
        - {label: "HeaderLogo1", name: "headerLogo1", widget: "image"}
        - {label: "HeaderLogo2", name: "headerLogo2", widget: "image"}
        - {label: "HeaderLogo3", name: "headerLogo3", widget: "image"}
        - {label: "HeaderLogo4", name: "headerLogo4", widget: "image"}
        - {label: "Section1Name", name: "section1Name", widget: "string"}
        - {label: "Section1Title", name: "section1Title", widget: "string"}
        - {label: "Section1Abstract", name: "section1Abstract", widget: "text"}
        - {label: "Slider1Slide1Title", name: "slider1Slide1Title", widget: "string"}
        - {label: "Slider1Slide1Abstract", name: "slider1Slide1Abstract", widget: "text"}
        - {label: "Slider1Slide1Image", name: "slider1Slide1Image", widget: "image"}
        - {label: "Slider1Slide2Title", name: "slider1Slide2Title", widget: "string"}
        - {label: "Slider1Slide2Abstract", name: "slider1Slide2Abstract", widget: "text"}
        - {label: "Slider1Slide2Image", name: "slider1Slide2Image", widget: "image"}
        - {label: "Slider1Slide3Title", name: "slider1Slide3Title", widget: "string"}
        - {label: "Slider1Slide3Abstract", name: "slider1Slide3Abstract", widget: "text"}
        - {label: "Slider1Slide3Image", name: "slider1Slide3Image", widget: "image"}
        - {label: "Slider1Slide4Title", name: "slider1Slide4Title", widget: "string"}
        - {label: "Slider1Slide4Abstract", name: "slider1Slide4Abstract", widget: "text"}
        - {label: "Slider1Slide4Image", name: "slider1Slide4Image", widget: "image"}
        - {label: "Slider1Slide5Title", name: "slider1Slide5Title", widget: "string"}
        - {label: "Slider1Slide5Abstract", name: "slider1Slide5Abstract", widget: "text"}
        - {label: "Slider1Slide5Image", name: "slider1Slide5Image", widget: "image"}
        - {label: "CaseHistoryName", name: "caseHistoryName", widget: "string"}
        - {label: "CaseHistoryTitleSection", name: "caseHistoryTitleSection", widget: "string"}
        - {label: "CaseHistoryBgText", name: "caseHistoryBgText", widget: "string"}
        - {label: "CaseHistoryTitle", name: "caseHistoryTitle", widget: "string"}
        - {label: "CaseHistoryAbstract", name: "caseHistoryAbstract", widget: "text"}
        - {label: "CaseHistoryTestimonialDescription", name: "caseHistoryTestimonialDescription", widget: "text"}
        - {label: "CaseHistoryTestimonialName", name: "caseHistoryTestimonialName", widget: "string"}
        - {label: "CaseHistoryTestimonialPosition", name: "caseHistoryTestimonialPosition", widget: "string"}
        - {label: "CaseHistoryLink", name: "caseHistoryLink", widget: "string"}
        - {label: "CaseHistoryImage", name: "caseHistoryImage", widget: "image"}
        - {label: "Section2Name", name: "section2Name", widget: "string"}
        - {label: "Section2Title", name: "section2Title", widget: "string"}
        - {label: "Section2Abstract", name: "section2Abstract", widget: "text"}
        - {label: "Section2Logo1", name: "section2Logo1", widget: "image"}
        - {label: "Section2Logo2", name: "section2Logo2", widget: "image"}
        - {label: "Section2Logo3", name: "section2Logo3", widget: "image"}
        - {label: "Section2Logo4", name: "section2Logo4", widget: "image"}
        - {label: "Section2Logo5", name: "section2Logo5", widget: "image"}
        - {label: "Section2Logo6", name: "section2Logo6", widget: "image"}
        - {label: "Cta1Title", name: "cta1Title", widget: "string"}
        - {label: "Cta1Link", name: "cta1Link", widget: "string"}
        - {label: "Section3Title", name: "section3Title", widget: "string"}
        - {label: "Section3Abstract", name: "section3Abstract", widget: "text"}
        - {label: "Slider2slide1Title", name: "slider2slide1Title", widget: "string"}
        - {label: "Slider2slide1BgText", name: "slider2slide1BgText", widget: "string"}
        - {label: "Slider2slide1Abstract", name: "slider2slide1Abstract", widget: "text"}
        - {label: "Slider2slide1Image", name: "slider2slide1Image", widget: "image"}
        - {label: "Slider2slide2Title", name: "slider2slide2Title", widget: "string"}
        - {label: "Slider2slide2BgText", name: "slider2slide2BgText", widget: "string"}
        - {label: "Slider2slide2Abstract", name: "slider2slide2Abstract", widget: "text"}
        - {label: "Slider2slide2Image", name: "slider2slide2Image", widget: "image"}
        - {label: "Slider2slide3Title", name: "slider2slide3Title", widget: "string"}
        - {label: "Slider2slide3BgText", name: "slider2slide3BgText", widget: "string"}
        - {label: "Slider2slide3Abstract", name: "slider2slide3Abstract", widget: "text"}
        - {label: "Slider2slide3Image", name: "slider2slide3Image", widget: "image"}
        - {label: "Slider2slide4Title", name: "slider2slide4Title", widget: "string"}
        - {label: "Slider2slide4BgText", name: "slider2slide4BgText", widget: "string"}
        - {label: "Slider2slide4Abstract", name: "slider2slide4Abstract", widget: "text"}
        - {label: "Slider2slide4Image", name: "slider2slide4Image", widget: "image"}
        - {label: "Section4Name", name: "section4Name", widget: "string"}
        - {label: "Section4Title", name: "section4Title", widget: "string"}
        - {label: "Section4Abstract", name: "section4Abstract", widget: "text"}
        - {label: "Section4IconBox1", name: "section4IconBox1", widget: "image"}
        - {label: "Section4TitleBox1", name: "section4TitleBox1", widget: "string"}
        - {label: "Section4AbstractBox1", name: "section4AbstractBox1", widget: "text"}
        - {label: "Section4IconBox2", name: "section4IconBox2", widget: "image"}
        - {label: "Section4TitleBox2", name: "section4TitleBox2", widget: "string"}
        - {label: "Section4AbstractBox2", name: "section4AbstractBox2", widget: "text"}
        - {label: "Section4IconBox3", name: "section4IconBox3", widget: "image"}
        - {label: "Section4TitleBox3", name: "section4TitleBox3", widget: "string"}
        - {label: "Section4AbstractBox3", name: "section4AbstractBox3", widget: "text"}
        - {label: "Section4IconBox4", name: "section4IconBox4", widget: "image"}
        - {label: "Section4TitleBox4", name: "section4TitleBox4", widget: "string"}
        - {label: "Section4AbstractBox4", name: "section4AbstractBox4", widget: "text"}
        - {label: "Section4IconBox5", name: "section4IconBox5", widget: "image"}
        - {label: "Section4TitleBox5", name: "section4TitleBox5", widget: "string"}
        - {label: "Section4AbstractBox5", name: "section4AbstractBox5", widget: "text"}
        - {label: "Section4IconBox6", name: "section4IconBox6", widget: "image"}
        - {label: "Section4TitleBox6", name: "section4TitleBox6", widget: "string"}
        - {label: "Section4AbstractBox6", name: "section4AbstractBox6", widget: "text"}
        - {label: "Section5Title", name: "section5Title", widget: "string"}
        - {label: "Section5Abstract", name: "section5Abstract", widget: "text"}
        - {label: "Cta2Title", name: "cta2Title", widget: "string"}
        